### ISSUE TITLE
Configure Jest in the core project

### ISSUE THREAD

**Issue by Fabianopb** [Fabianopb/create-mern-ts-app#12]
We need to set up unit tests in the core project (this excludes the `template` folder). It would be nice to use Jest to keep consistency with other projects.

Also It would be nice to have at least one unit test for `create-mern-ts-app.js` so we can have the testing suite up and running.

**Comment by Jayadev6191** [comment]
I can take this! :)

**Comment by Fabianopb** [comment]
Thanks @Jayadev6191 :)

**Comment by Jayadev6191** [comment]
Hey @Fabianopb. This is new to me and I've been playing around with travis to set it up for one of my own apps and do that same to `create-mern-ts-app`.

I will be looking at this over the weekend and happy to work on it even after Hacktoberfest. Let me know if you want to assign it to someone else. I can un-claim it.

Thanks!
Jay

**Comment by Fabianopb** [comment]
Alright, no problem, I was just checking!

Just to contextualize a bit more, this issue is for basically setting up Jest in the root package.json for testing the file `create-mern-ts-app.js` and ignore the `template` folder. You actually don't even have to write unit tests, just a place holder `expect(true).toBeThruthy();` will do here, just to get the test suite up and running! :)

Travis is part of the next step described in https://github.com/Fabianopb/create-mern-ts-app/issues/13

Any questions just shoot! Thanks again!

**Comment by Jayadev6191** [comment]
Hi @Fabianopb , I have created a simple PR which has jest added as a dev dependency and and test option under scripts in package.json file. Please review and let me know if it looks good for the basic setup.

Thanks,
Jayadev

**Comment by Fabianopb** [comment]
Resolved, closing.
