### ISSUE TITLE
Node greater than v8

### ISSUE THREAD

**Issue by benjaminmateev** [Fabianopb/create-mern-ts-app#36]
Hello, I saw that you had an issue in Oct that was merged to allow for higher node versions than 8 but in the current master it is back to the state before that merge. Not sure what happened there but I have the issue that I cannot use the installer locally without making that code change myself. 

Am I missing something?

**Comment by Fabianopb** [comment]
Hi @benjaminmateev thanks for opening this issue!

Checking the master it seems that we are allowing node greater or equal than v8: https://github.com/Fabianopb/create-mern-ts-app/blob/master/package.json#L7

How exactly are you trying to "use the installer locally"?

**Comment by benjaminmateev** [comment]
I tried both the npx path and then installing via npm and running the installer manually.
`npx create-mern-ts-app .`
`npm i create-mern-ts-app`

It only worked for me, once I changed the package.json in the template folder. Not sure why thats the case though.

**Comment by Fabianopb** [comment]
Oh, I got it now, you're right! That's a bug!

The issue you were referring is https://github.com/Fabianopb/create-mern-ts-app/issues/7 which changed the node version in the root package.json, but not in the template.

Would you be willing to submit a fix for that? :)

**Comment by benjaminmateev** [comment]
Sure thing!

**Comment by Fabianopb** [comment]
Thanks again @benjaminmateev , `v1.3.1` published with your fix!

**Comment by benjaminmateev** [comment]
Thank you! Works like a charm now
